[tool.poetry]
name = "mindcalc"
version = "0.1.0"
description = ""
authors = ["Stefano Torre <stefano.torre@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyqt6 = "^6.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
